#ifndef ROUTING_DEVICE_IDS_H
#define ROUTING_DEVICE_IDS_H

#define SIMPLE_OBJECT_DEVICE_ID			0x01
#define HEARTBEAT_DEVICE_ID				0x02
#define SERVO_DEVICE_ID					0x03
#define MOTOR_CONTROL_DEVICE_ID			0x04
#define INPUT_HANDLER_DEVICE_ID			0x05
#define DISTANCE_SENSOR_DEVICE_ID		0x05


#define TEST_COMMAND_ROUTER_APP_DEVICE_ID		0x1001
#define GODZUKI_SENSOR_PLATFORM_DEVICE_ID		0x1002

#define   GLOBAL_COMMAND_STATUS_OK		0x0000
#define   GLOBAL_COMMAND_STATUS_FAIL	0x0001
#define   GLOBAL_COMMAND_BROADCAST		0x0063
#define   GLOBAL_COMMAND_STATUS			0xffff

#endif
