#ifndef ROUTING_DEVICE_IDS_H
#define ROUTING_DEVICE_IDS_H

#define SIMPLE_OBJECT_DEVICE_ID			0x01
#define HEARTBEAT_DEVICE_ID				0x02
#define SERVO_DEVICE_ID					0x03
#define MOTOR_CONTROL_DEVICE_ID			0x04
#define INPUT_HANDLER_DEVICE_ID			0x05
#define DISTANCE_SENSOR_DEVICE_ID		0x05

#define   GLOBAL_COMMAND_STATUS		0xffff

#endif
