#ifndef ROUTING_DEVICE_IDS_H
#define ROUTING_DEVICE_IDS_H

#define SIMPLE_OBJECT_DEVICE_ID			0x01
#define HEARTBEAT_DEVICE_ID				0x02
#define SERVO_DEVICE_ID					0x03
#define MOTOR_CONTROL_DEVICE_ID			0x04
#define INPUT_HANDLER_DEVICE_ID			0x05
#define DISTANCE_SENSOR_DEVICE_ID		0x06
#define CAMERA_DEVICE_ID				0x07
#define SD_CARD_DEVICE_ID				0x08

#define CNC_APP_DEVICE_ID						97
#define TEST_COMMAND_ROUTER_APP_DEVICE_ID		98
#define GODZUKI_SENSOR_PLATFORM_DEVICE_ID		99

#define   GLOBAL_COMMAND_STATUS_OK		00
#define   GLOBAL_COMMAND_STATUS_FAIL	01

#define   COMMAND_ID_GLOBAL_NONE			97
#define   COMMAND_ID_GLOBAL_REQUEST_STATUS	98
#define   COMMAND_ID_GLOBAL_BROADCAST		99

#endif
